source:
  host: localhost
  port: 3306
  database: source_db
  username: '' # DO NOT use 'root' in production
  password: '' # Store passwords securely, not in this file
  connectionTimeout: 30
  maxPoolSize: 100
  minPoolSize: 0
  useSSL: true # Always use SSL in production
  sslCertPath: ''
  sslKeyPath: ''
  sslCaPath: ''
  additionalParameters: {}
target:
  host: localhost
  port: 3306
  database: target_db
  username: '' # DO NOT use 'root' in production
  password: '' # Store passwords securely, not in this file
  connectionTimeout: 30
  maxPoolSize: 100
  minPoolSize: 0
  useSSL: true # Always use SSL in production
  sslCertPath: ''
  sslKeyPath: ''
  sslCaPath: ''
  additionalParameters: {}
mode: Full
syncSchema: true
previewSchemaChanges: true
batchSize: 1000
maxRetryAttempts: 3
retryDelayMs: 1000
conflictResolution: SourceWins
includeSchemas: []
excludeSchemas: []
includeTables: []
excludeTables: []
parallelThreads: 1
enableCheckpointing: false
checkpointPath: ./checkpoints
emailNotification:
  enabled: false
  smtpServer: ''
  smtpPort: 25
  useSsl: true
  username: ''
  password: ''
  fromAddress: ''
  toAddresses: []
dataMaskingRules: []
